package fr.perso.exemple.batchexemplekotlin.stepexampletwo.configuration

import fr.perso.exemple.batchexemplekotlin.stepexampleone.processor.StepExampleOneItemProcessor
import fr.perso.exemple.batchexemplekotlin.stepexampletwo.processor.StepExampleTwoItemProcessor
import org.springframework.batch.core.repository.JobRepository
import org.springframework.batch.item.file.FlatFileItemReader
import org.springframework.batch.item.file.FlatFileItemWriter
import org.springframework.beans.factory.annotation.Qualifier
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.transaction.PlatformTransactionManager

@Configuration
class StepExampleTwoConfiguration
